# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"

    filter_sets:
      thumb:
        quality: 75
        filters:
          thumbnail:
            size: [253, 253]
            mode: outbound
            allow_upscale: true
      medium:
        quality: 90
        filters:
          thumbnail:
            size: [800, 500]
            mode: outbound
            allow_upscale: true
